# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\"\x99\x01\n\x14ProductCandleRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x13\n\x0bgranularity\x18\x02 \x01(\x05\x12\x15\n\x08requests\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x1e\n\x11\x64\x61ta_points_limit\x18\x04 \x01(\x05H\x01\x88\x01\x01\x42\x0b\n\t_requestsB\x14\n\x12_data_points_limit\"\xbd\x01\n\x15ProductCandleResponse\x12=\n\x0fproduct_candles\x18\x01 \x03(\x0b\x32$.ProductCandleResponse.ProductCandle\x1a\x65\n\rProductCandle\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x0b\n\x03low\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x32Y\n\x13ProductsDataService\x12\x42\n\x11GetProductCandles\x12\x15.ProductCandleRequest\x1a\x16.ProductCandleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTCANDLEREQUEST']._serialized_start=19
  _globals['_PRODUCTCANDLEREQUEST']._serialized_end=172
  _globals['_PRODUCTCANDLERESPONSE']._serialized_start=175
  _globals['_PRODUCTCANDLERESPONSE']._serialized_end=364
  _globals['_PRODUCTCANDLERESPONSE_PRODUCTCANDLE']._serialized_start=263
  _globals['_PRODUCTCANDLERESPONSE_PRODUCTCANDLE']._serialized_end=364
  _globals['_PRODUCTSDATASERVICE']._serialized_start=366
  _globals['_PRODUCTSDATASERVICE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
