
candles:
  product_ids: 
    - "BTC-USD"
  event_type: "productCandleData"
  subscription_name: "product-candle-data"
  event_grid_endpoint: /eventgrid/candles
  endpoint: "https://insights.azurewebsites.net/candles"